name: zscaler test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Test if you are behind ZScaler proxy
      - name: ZScaler test
        run: |
          curl -s https://ip.zscaler.com/ | grep "The request received"
